stages:
  - build
  - test
  - deploy

Compilation:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/

Test_Add:
  stage: test
  dependencies:
    - Compilation
  script:
    - ./build/src/calculator add 2 3

Test_sub:
  stage: test
  dependencies:
    - Compilation
  script:
    - ./build/src/calculator sub 3 -2

Test_mul:
  stage: test
  dependencies:
    - Compilation
  script:
    - ./build/src/calculator mul 5 5

Test_div:
  stage: test
  dependencies:
    - Compilation
  script:
    - ./build/src/calculator div 1 5

Test_car:
  stage: test
  dependencies:
    - Compilation
  script:
    - ./build/src/calculator car 5

Deployment:
  stage: deploy
  script:
    - echo "Déploiement de la solution"
